# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nevinzheng/conwayCPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nevinzheng/conwayCPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.7.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nevinzheng/conwayCPP/CMakeFiles /Users/nevinzheng/conwayCPP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nevinzheng/conwayCPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tst

# Build rule for target.
tst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst
.PHONY : tst

# fast build rule for target.
tst/fast:
	$(MAKE) -f CMakeFiles/tst.dir/build.make CMakeFiles/tst.dir/build
.PHONY : tst/fast

#=============================================================================
# Target rules for targets named t_GameOfLife

# Build rule for target.
t_GameOfLife: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_GameOfLife
.PHONY : t_GameOfLife

# fast build rule for target.
t_GameOfLife/fast:
	$(MAKE) -f CMakeFiles/t_GameOfLife.dir/build.make CMakeFiles/t_GameOfLife.dir/build
.PHONY : t_GameOfLife/fast

#=============================================================================
# Target rules for targets named conwayCPP

# Build rule for target.
conwayCPP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conwayCPP
.PHONY : conwayCPP

# fast build rule for target.
conwayCPP/fast:
	$(MAKE) -f src/CMakeFiles/conwayCPP.dir/build.make src/CMakeFiles/conwayCPP.dir/build
.PHONY : conwayCPP/fast

#=============================================================================
# Target rules for targets named GameOfLife

# Build rule for target.
GameOfLife: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GameOfLife
.PHONY : GameOfLife

# fast build rule for target.
GameOfLife/fast:
	$(MAKE) -f src/CMakeFiles/GameOfLife.dir/build.make src/CMakeFiles/GameOfLife.dir/build
.PHONY : GameOfLife/fast

u_tst/t_GameOfLife.o: u_tst/t_GameOfLife.cpp.o

.PHONY : u_tst/t_GameOfLife.o

# target to build an object file
u_tst/t_GameOfLife.cpp.o:
	$(MAKE) -f CMakeFiles/t_GameOfLife.dir/build.make CMakeFiles/t_GameOfLife.dir/u_tst/t_GameOfLife.cpp.o
.PHONY : u_tst/t_GameOfLife.cpp.o

u_tst/t_GameOfLife.i: u_tst/t_GameOfLife.cpp.i

.PHONY : u_tst/t_GameOfLife.i

# target to preprocess a source file
u_tst/t_GameOfLife.cpp.i:
	$(MAKE) -f CMakeFiles/t_GameOfLife.dir/build.make CMakeFiles/t_GameOfLife.dir/u_tst/t_GameOfLife.cpp.i
.PHONY : u_tst/t_GameOfLife.cpp.i

u_tst/t_GameOfLife.s: u_tst/t_GameOfLife.cpp.s

.PHONY : u_tst/t_GameOfLife.s

# target to generate assembly for a file
u_tst/t_GameOfLife.cpp.s:
	$(MAKE) -f CMakeFiles/t_GameOfLife.dir/build.make CMakeFiles/t_GameOfLife.dir/u_tst/t_GameOfLife.cpp.s
.PHONY : u_tst/t_GameOfLife.cpp.s

u_tst/tst.o: u_tst/tst.cpp.o

.PHONY : u_tst/tst.o

# target to build an object file
u_tst/tst.cpp.o:
	$(MAKE) -f CMakeFiles/tst.dir/build.make CMakeFiles/tst.dir/u_tst/tst.cpp.o
.PHONY : u_tst/tst.cpp.o

u_tst/tst.i: u_tst/tst.cpp.i

.PHONY : u_tst/tst.i

# target to preprocess a source file
u_tst/tst.cpp.i:
	$(MAKE) -f CMakeFiles/tst.dir/build.make CMakeFiles/tst.dir/u_tst/tst.cpp.i
.PHONY : u_tst/tst.cpp.i

u_tst/tst.s: u_tst/tst.cpp.s

.PHONY : u_tst/tst.s

# target to generate assembly for a file
u_tst/tst.cpp.s:
	$(MAKE) -f CMakeFiles/tst.dir/build.make CMakeFiles/tst.dir/u_tst/tst.cpp.s
.PHONY : u_tst/tst.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... install/local"
	@echo "... test"
	@echo "... tst"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... t_GameOfLife"
	@echo "... conwayCPP"
	@echo "... GameOfLife"
	@echo "... u_tst/t_GameOfLife.o"
	@echo "... u_tst/t_GameOfLife.i"
	@echo "... u_tst/t_GameOfLife.s"
	@echo "... u_tst/tst.o"
	@echo "... u_tst/tst.i"
	@echo "... u_tst/tst.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

